
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: cybersecurity_development


test:
  <<: *default
  database: cybersecurity_test


production:
  primary: &primary_production
    <<: *default
    database: cybersecurity_production
    username: cybersecurity
    password: <%= ENV["CYBERSECURITY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: cybersecurity_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: cybersecurity_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: cybersecurity_production_cable
    migrations_paths: db/cable_migrate
