default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: 127.0.0.1
  port: 5432
  username: djg
  password: "Wyld4n20!3"

production:
  primary:
    <<: *default
    database: cybersecurity_production
    schema_search_path: public

  # Solid Queue uses its own schema
  queue:
    <<: *default
    database: cybersecurity_production
    schema_search_path: solid_queue,public

  # Solid Cable uses its own schema
  cable:
    <<: *default
    database: cybersecurity_production
    schema_search_path: solid_cable,public

  # Solid Cache uses its own schema
  cache:
    <<: *default
    database: cybersecurity_production
    schema_search_path: solid_cache,public
